import React, { useEffect, useState } from 'react';

import Head from 'next/head';
import '../styles/globals.css';
import { MainLayout } from '@/components';

export default function App({ Component, pageProps }) {
  const [showing, setShowing] = useState(false);

  useEffect(() => {
    setShowing(true);
  }, []);

  if (!showing) {
    return null;
  }

  if (typeof window === 'undefined') {
    return <></>;
  } else {
    return (
      <>
        <Head>
          <title>Muhammad Azizul Hoque Jiku</title>
          {/* <meta content="width=device-width, initial-scale=1" name="viewport" /> */}
          {/* <meta
            content="width=device-width, initial-scale=1, minimum-scale=1"
            name="viewport"
          /> */}{' '}
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
          />
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <MainLayout>
          <Component {...pageProps} />
        </MainLayout>
      </>
    );
  }
}
