import React from 'react';
// external import
import Head from 'next/head';
// internal import
import { MainPage } from '@/components';

const Page = () => {
  return (
    <>
      <Head>
        <title>Muhammad Azizul Hoque Jiku</title>
        {/* <meta content="width=device-width, initial-scale=1" name="viewport" /> */}
        {/* <meta
          content="width=device-width, initial-scale=1, minimum-scale=1"
          name="viewport"
        /> */}
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
        />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainPage />
    </>
  );
};

export default Page;
