import React from 'react';
import Head from 'next/head';
import { ProjectDetails } from '@/components';
import { projectsData } from '@/db';

const Page = ({ project }) => {
  const projectInfo = project;

  return (
    <>
      <Head>
        <title>Muhammad Azizul Hoque Jiku</title>
        {/* <meta content="width=device-width, initial-scale=1" name="viewport" /> */}
        {/* <meta
          content="width=device-width, initial-scale=1, minimum-scale=1"
          name="viewport"
        /> */}
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
        />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ProjectDetails projectInfo={projectInfo} />
    </>
  );
};

export default Page;

export const getStaticPaths = async () => {
  const projects = projectsData;
  const paths = projects.map((item) => {
    return {
      params: {
        title: item?.projectTitle?.toString(),
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (ctx) => {
  const title = ctx?.params?.title?.split('%20')?.join(' ');

  const project = projectsData?.filter(
    (item) => item?.projectTitle === title
  )[0];

  return {
    props: {
      project,
    },
  };
};
